--!strict

return {
	Modes = {
		["1v1"] = { LengthScale = 1.00, WidthScale = 1.00 },
		["2v2"] = { LengthScale = 1.00, WidthScale = 1.00 },
		["3v3"] = { LengthScale = 1.05, WidthScale = 1.05 },
		["4v4"] = { LengthScale = 1.15, WidthScale = 1.20 },
		["5v5"] = { LengthScale = 1.25, WidthScale = 1.35 },
	},

	BaseLength = 96,
	BaseWidth = 56,
	FloorThickness = 1,
	WallHeight = 7,
	WallThickness = 2,
	GoalWidth = 18,
	GoalDepth = 9,
	BallHeight = 2.1,
	PlayerSpawnOffset = 24,
}
